# baseURL = "/"
# languageCode = "zh-CN"
# title = "RON的家"
# # theme = "webstack-hugo"
# theme = "biobt"

# preserveTaxonomyNames = true
# disablePathToLower = true
# hasCJKLanguage = true
# copyright = ""
# [params]
#   author = "luvisiki"
#   description = "luvisiki的导航页"
# [params.search]
#   enable = true
# [params.darkmode]
#   enable = false

baseURL               = "/"
languageCode          = "zh-CN"
title                 = "luvisiki的导航页"
theme                 = "biobt"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"					# 站点静态文件保存目录


[params]
    author        = "luvisiki"
    description   = "Luvisiki的导航页"
    upload        = "https://github.com/luvisiki"  # 左侧导航栏的"网站提交"
    about         = "https://shumlab.com/cookbook/webstack-hugo"	# 左侧导航栏的"关于导航"页面(./about)
    # repository    = "https://github.com/shenweiyan/WebStack-Hugo"  
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "May you be immortal."				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    # logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    logosPath     = ""			# 网站每个导航地址logo存放地址

    defaultLogo   = "assets/images/Web.png"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = true					# 默认站点为深色(夜间)模式
    yiyan         = true                         		# 默认启用一言服务

[params.seo]    
    baiduhmid       = 'efccc04cb44fc49faddac5876180b369'	# 百度统计 hm.src 的 ID
    baiduSiteVer    = 'codeva-cCAOSG8MBO'			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/back-light.jpg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/back.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/Close.png"
    logoCollapseDark  = "assets/images/Close.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '内容全部来自开源社区.MAIL：luvisiki_99@qq.com <br/>&copy; 2023 - {year} By [原仓库地址](https://github.com/shenweiyan/WebStack-Hugo) | [MY Github](https://github.com/luvisiki) <br/>'
