baseURL = "/"
languageCode = "zh-CN"
title = "RON的家"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "iplaycode"
  description = "Webstack Hugo"
[params.search]
  enable = true
[params.darkmode]
  enable = false